package com.luffy.testautomation.prjhelpers;

public interface ButtonHelpers {

    String androidContinueButtonId = "multiStateButton";
    String mobileAliasContinueButtonId = "mobileAlias_continueButton_identifier";
    String androidAlertTitle = "android:id/alertTitle";
    String androidPopUpTittle = "titleTextView";
    String androidButton1Id = "android:id/button1";
    String androidButton2Id = "android:id/button2";
    String androidButton3Id = "android:id/button3";
    String androidContentContainer = "android:id/content";
    String androidPermissionAllowForegroundOnlyButton = "permission_allow_foreground_only_button";
    String androidPermissionDeclineButton = "permission_deny_button";
    String androidMessageDeleteButtonId = "action_delete";
    String androidMessageReplyButtonId = "action_reply";
    String androidInteracTransferMenuId = "interacTransferMenu";
    String androidDoneButtonId = "action_done";
    String androidCommonTransferInputId = "proxyNumberEditText";
    String androidActionNextButtonId = "action_next";
    String androidSubmitId = "submitButton";
    String androidDeleteButtonId = "deleteButtonLayout";
    String androidSnackbarId = "snackbar_text";
    String androidProgressBarId = "loadingProgressBar";
    String androidMauthProgressBarId = "base_progress_view";
    String androidProgressBarClassName = "ProgressBar";
    String androidOkButtonId = "okButton";
    String androidCancelButtonId = "cancelButton";
    String androidCancelText = "Cancel";
    String androidNextButtonId = "android:id/next";
    String androidPrevButtonId = "android:id/prev";
    String androidMonthViewButtonId = "android:id/month_view";
    String androidPasswordContinueButtonId = "Continue";
    String androidFromAccountId = "fromAccount";
    String androidToAccountId = "toAccount";
    String androidToPayeeId = "toPayee";
    String androidFromAccountNumberId = "accountNumberText";
    String androidFromAccountBalanceId = "amountText";
    String androidTransactionAmountId = "enterAmountRow";
    String androidTransactionAmountTextId = "enterAmount";
    String androidTransactionAmountInputId = "amountEditText";
    String androidRecipientReferenceInputId = "editTextReferenceNote";
    String androidConfirmTransferInfoId = "confirmTransferLinearLayout";
    String androidMakeAnotherTransferButtonId = "anotherTransferButton";
    String androidPrimaryBtn = "innerSecondaryButton";
    String androidSecondaryBtn = "innerButton";
    String androidScreenError = "tv_error";
    String androidNavigateBackXpath = "//*[contains(@content-desc,'Navigate Back')]";
    String androidNavigateUpXpath = "//*[contains(@content-desc,'Navigate up')]";
    String androidCloseMobileTokenButton = "closeButton";
    String androidPrimaryButtonId = "primary_button";
    String androidHelpButton = "pin_help_button";
    String androidCloseButton = "com.android.chrome:id/close_button";
    String mAuthAndroidProgressBarId = "base_progress_bar";
    String androidOfflineCloseButton = "Close";
    String getAndroidTimerCloseButtonXpath = "//android.widget.ImageButton[@content-desc='Close']";
    String androidCancelRegistrationButtonId = "mauth_menu_registration_cancel";
    String androidSwitchWidgetButtonId = "com.android.settings:id/switch_widget";
    String androidAllowButtonId = "permission_allow_button";
    String androidDenyButtonId = "permission_deny_button";
    String backButtonId = "Back";
    String androidBackXpath = "//android.widget.ImageButton[@content-desc='Back']";
    String androidErrorLogoId = "placeholder_image_view";
    String androidErrorMessageId = "title_text_view";
    String androidEnterVerificationXpath =
            "//android.widget.LinearLayout[contains(@resource-id,'verify_details_component_container')]//android.widget.EditText";
    String androidHelpVisitOurWebsiteButtonId = "help_secondary_button";
    String androidSelectVerificationOptionXpath =
            "//android.view.ViewGroup/android.widget.TextView[contains(@text,'";
    String androidNtdHelpContainerId = "m_auth_registration_help_verify_identity";
    String androidNtdHelpIconXpath = "//android.widget.ImageView[contains(@content-desc,'";
    String androidNtdHintXpath = "//android.widget.LinearLayout[contains(@content-desc,'";
    String androidCrossButtonXpath = "//*[contains(@content-desc,'Close')]";
    String androidCancelProvisioningButtonId = "mauth_menu_provisioning_cancel";
    String androidMauthCommonHelpCloseButtonId = "bottomSheetCloseButton";
    String androidLargeSpinnerId = "largeSpinner";
    String androidLoadingProgressIconId = "progressBar";
    String androidPrimaryBtnId = "primaryButton";
    String androidSecondaryBtnId = "secondaryButton";
    String androidHelpIconId = "sInputFieldIcon";
    String androidInlineErrorId = "messageTextView";
    String androidDisplayInputField = "sInputFieldText";

    String iosOkUppercaseName = "OK";
    String iosDoneButtonMoveMoneyId = "amountview.amount.edit.done";
    String iosDoneButtonAddBeneId = "ref.note.done";
    String iosTextViewId = "ref.note.text";
    String iosSubmitButtonId = "submit_button";
    String iosPayNowContinueButtonName = "movemoney.footer.progress-button";
    String iosPayNowConfirmButtonName = "movemoney.verifyscreen.progress-button";
    String iosPayNowCancelButtonName = "movemoney.verifyscreen.cancel-button";
    String iosConfirmButtonName = "Confirm";
    String iosMauthCloseButtonId = "closeAction";
    String iosPrimaryButton = "primaryAction";
    String iosSecondaryButton = "secondaryAction";
    String iosSecondButton = "secondarybutton";
    String iosNavigateBackId = "Navigate Back";
    String iosCheckboxButtonId = "checkbox_button";

    String iosDoneButtonId = "Done";
    String iosReturnButtonId = "Return";
    String iosFromAccountIdOrName = "duitnow.accountview.from";
    String iosToAccountIdOrName = "duitnow.contactview.to";
    String iosFromAccountNumberIdOrName = "account.cell.item.account.number";
    String iosFromAccountContainerIdOrName = "account.cell.item";
    String iosPayeeAccountNumberIdOrName = "account.cell.item.account.balance";
    String iosTransactionAmountIdOrName = "duitnow.amountview.amount";
    String iosTransactionAmountInputIdOrName = "transfer.amountview.amount.edit.from";
    String iosConfirmationIdOrName = "Thank you";
    String iosLoaderId = "loader_Id";
    String iosSnackbarId = "toast_message_label";
    String iosLastLogonSnackbarId = "bannerview-message";
    String iosContinueId = "primarybutton";
    String iosMauthLoaderName = "Loading";
    String iosContinueRegistrationButtonId = "Continue";
    String iosCancelRegistrationButtonId = "create_credentials_cancel";
    String iosToastMessageId = "toast_message_label";
    String iosCancelButtonId = "tertiarybutton";
    String iosErrorLogoId = "m_auth_sdk_warning_large";
    String iosErrorMessageId = "titleLabel";
    String androidPopupCloseXpath =
            "//android.view.ViewGroup[contains(@resource-id,'toolbar_view')]/android.widget.ImageButton";
    String iosNtdContinueButtonXpath =
            "//XCUIElementTypeButton[@name='create_credentials_continueaction']";
    String iosPopupCloseName = "mauth_accessibility_its_close_button";
    String iosHelpVisitOurWebsiteButtonId = "help_overlay_secondary_button";
    String iosNtdSelectVerificationXpath =
            "//XCUIElementTypeTable [@name='verify_identity_select_verification_title']//XCUIElementTypeCell[contains(@label, '";
    String iosNtdHelpAlertId = "HelpAlert";
    String iosCancelProvisioningButtonId = "cancelButton";
    String iosYesButtonId = "Yes";
    String iosNoButtonId = "No";
    String iosDskStepDownDismissButtonId = "close_help";
    String iosMauthCommonHelpCloseButtonId = "dismissButton";
    String iosMauthCommonInlineErrorId = "inlinestatus-text";
    String iosMauthCommonHelpIconId = "displayinputfield-imageview";
    String iosThirdButton = "tertiarybutton";
    String iosMauthCommonHelpBottomSheetId = "ModalSheetHeader";
    String iosMauthHelpTextId = "titleLabel";
    String iosDeleteButtonId = "delete";
    String iosBannerCloseButton = "//XCUIElementTypeButton[@name='Close']";

    // Wealth X
    String commonToolbarTitleId = "text_toolbar_title";
    String commonOrderTypeLabelId = "text_order_type_label";
    String commonPriceLabelId = "text_price_label";
    String commonPriceLabelTextId = "textview_price_label";
    String commonOrderTypeInputId = "text_order_type_input";
    String commonPriceInputId = "text_price_input";
    String commonCloseButtonId = "Dismiss";
    String commonButtonBidPriceId = "button_bid_price";
    String commonButtonAskPriceId = "button_ask_price";
    String commonDayLowDayHighPriceId = "text_price_day_low_day_high";
    String commonPriceTimeId = "text_date";
    String commonCoolingOffPeriodHeaderId = "text_sub_title_price_model";
    String commonBackButtonId = "button_toolbar_back";
    String commonAccountSelectionNameId = "text_account_selection_name";
    String commonAccountSelectionNumberId = "text_account_selection_number";
    String commonTransactionTypeId = "text_instruction";
    String commonOrderStatusId = "text_order_status";
    String commonStockNameId = "text_stock_name";
    String commonStockCodeId = "text_stock_code";
    String commonHelpIconId = "button_toolbar_question";
    String commonRefreshIconId = "button_toolbar_refresh";
    String iosBannerDescriptionId = "bannerview-message";
    String androidBannerDescriptionId = "bannerDescription";
    String iosLearnMoreButtonId = "learn-more-quote-banner";
    String androidLearnMoreButtonId = "buttonTwo";
    String iosDismissButtonId = "dismiss-quote-banner";
    String androidDismissButtonId = "buttonOne";
    String commonToolbarCloseId = "button_toolbar_close";
    String iosToolbarDoneId = "Done";
    String androidToolBarDoneId = "button_toolbar_done";
    String commonTextTodayId = "text_today";
    String commonImportantNotesId = "textview_important_notes";
    String commonInstructionId = "review_item_instruction";
    String inputAccountAliasId = "displayInputEditText";
    String androidBottomSheetListId = "title";
    String iosBottomSheetListClassName = "XCUIElementTypeStaticText";
    String iosBackButtonId = "mauth_accessibility_action_back";
    String commonDiscardButtonId = "Discard";
    String iosDisplayInputField = "displayinputfield-textfield";
    String commonLocalMutualFundIconName = "local_mutual_fund";
    String commonNextButtonName = "next_button";

    // UPI
    String continueButtonIos = "p2p_input_cta_continue";
    String confirmButtonIos = "accessibility_p2p_verify_screen_continue_button";
    String cancelButtonIosId = "Cancel";

    // Transaction Type Control
    String androidPopUpId = "popUpTitle";
    String disableLimitsPopUpName = "popup-container";

    String payeeDoneButton = "selectPayee_done_button";
    String androidBackButtonId = "Navigate up";
}
